import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} w-screen h-screen flex flex-col justify-between`}
      >
        <Navbar />

        <div className="flex flex-row w-full">
          <Sidebar />
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
